services:
  app:
    container_name: ML_managment
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:5300"
    env_file:
      - stack.env
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:80/health"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
    #   start_period: 60s
    networks:
      - app-network
    # depends_on:
    #   - db

  db:
    container_name: mashhad_leather_db
    image: postgres:latest
    restart: always
    env_file:
      - stack.env
    volumes:
      - /home/jenkins/volumes/mashhad_leather_db/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge